In [13]:
!unzip neuroxai_data.zip

Streaming output truncated to the last 5000 lines.
  inflating: neuroxai_data/Moderate/OAS1_0067_MR1/slice_30.png  
  inflating: neuroxai_data/Moderate/OAS1_0067_MR1/slice_31.png  
  inflating: neuroxai_data/Moderate/OAS1_0067_MR1/slice_4.png  
  inflating: neuroxai_data/Moderate/OAS1_0067_MR1/slice_5.png  
  inflating: neuroxai_data/Moderate/OAS1_0067_MR1/slice_6.png  
  inflating: neuroxai_data/Moderate/OAS1_0067_MR1/slice_7.png  
  inflating: neuroxai_data/Moderate/OAS1_0067_MR1/slice_8.png  
  inflating: neuroxai_data/Moderate/OAS1_0067_MR1/slice_9.png  
  inflating: neuroxai_data/Moderate/OAS1_0073_MR1/slice_0.png  
  inflating: neuroxai_data/Moderate/OAS1_0073_MR1/slice_1.png  
  inflating: neuroxai_data/Moderate/OAS1_0073_MR1/slice_10.png  
  inflating: neuroxai_data/Moderate/OAS1_0073_MR1/slice_11.png  
  inflating: neuroxai_data/Moderate/OAS1_0073_MR1/slice_12.png  
  inflating: neuroxai_data/Moderate/OAS1_0073_MR1/slice_13.png  
  inflating: neuroxai_data/Moderate/OAS1_0073_M

In [14]:
!pip install timm torch torchvision opencv-python scikit-learn


In [27]:
!python train.py

Using device: cuda
[INFO] Loaded 233 subjects
/content/train.py:35: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler()
/content/train.py:45: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
/content/train.py:60: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast():
Epoch 1/10 | Loss: 193.1106 | Val Acc: 55.88%
Epoch 2/10 | Loss: 162.8252 | Val Acc: 55.88%
Epoch 3/10 | Loss: 160.0942 | Val Acc: 55.88%
Epoch 4/10 | Loss: 153.8310 | Val Acc: 26.47%
Epoch 5/10 | Loss: 130.4453 | Val Acc: 58.82%
Epoch 6/10 | Loss: 66.9592 | Val Acc: 29.41%
Epoch 7/10 | Loss: 39.1637 | Val Acc: 32.35%
Epoch 8/10 | Loss: 23.5837 | Val Acc: 35.29%
Epoch 9/10 | Loss: 22.8964 | Val Acc: 32.35%
Epoch 10/10 | Loss: 21.7740 | Val Acc: 26.4

In [31]:
!python test_model.py

Using device: cuda
[INFO] Loaded 233 subjects
[INFO] Test samples: 36

================ TEST RESULTS ================
Overall Test Accuracy: 55.56%

Confusion Matrix:
[[10 13  2]
 [ 0  9  1]
 [ 0  0  1]]

Class-wise Accuracy:
Normal: 40.00%
Mild: 90.00%
Moderate: 100.00%

Classification Report:
              precision    recall  f1-score   support

      Normal     1.0000    0.4000    0.5714        25
        Mild     0.4091    0.9000    0.5625        10
    Moderate     0.2500    1.0000    0.4000         1

    accuracy                         0.5556        36
   macro avg     0.5530    0.7667    0.5113        36
weighted avg     0.8150    0.5556    0.5642        36

ROC-AUC (OvR): 0.8036


In [30]:
!python predict_subject.py



Prediction Results
------------------
Normal: 0.44%
Mild: 0.05%
Moderate: 99.51%
------------------
Final Prediction: Moderate
